language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: tbenbrahim-github
    token:
    secure: "hjYJxLqA2DuRBz46ey4/7Q7HRNDlcGX6qLku+vwIg6tVwU36Ygtj00ie7X6M1nMKS4Rt5CQqcS1pwBnbsMAX0SLBTl2yUq99QgJRrdf5Xlf64qCWh3X9KYvmH2F06RCZEI60XTabzq9JWoc+fL1aUaVPVnVG8IvexR9u7RTrcXv7/gqrd0dE2oQPB2wo6NNCNat/XBLjuFIWktfFzKvK3RRbrUNE7Drrx9wAFyYbUtK8mI6gyYmhWMlfPXNj6OEOStjG6Vjj5ptryGS0QyKCqWlGqZEpA8DexwRv5z50FxMWsapTJ6npxs2k7RKVTJRdXaGr6Xg9TO014RfVQCTnk9fNf4IJq22QdDnv0Bv7mHsSJztxh2bs3exUuLtqHY70nSX/Yf9DITUF2WjymzKFnKmvFigM9tEHsFUMNi3nRMJ++gisnC1lxkBOlhptoChmVvyQgrC+WBNuZH3qcm8IH2MiNWX1UcVqEA4bP2aba8qSIuVE0zGbpd+51rpQYSBQU2pJaeHZJuIXkoquT8hyruaayHjkVCDBMOYnNktklUhTQrmW/d8yoc+bXD34unruPjlZWDHnCitlo6HAQpwv8uTB7dqjTisJ3pNu2fw/hm+RCCuld7i7oIbpxrKv/iF1Mb/oLY0MSTC7Jv5Aun9i5GQvoV1EKJTBWZp9J4v4/yI="
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
