language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: tbenbrahim-github
    token:
      secure: gvHaa0IMX3aSZCn8oLzECuBMF1teyNf6wCPtsaJ7YjQSwbC3/xl558Qtfkhmopjiejp7Vs+YTmBRbqHQtxi4nyh1s+yqvqyGXNCHpQaOmuThJOimDUCULuksTqZSMKWU8lei5scF2ba65xE/c5Ao170u8O5wCL+UHQkq7JbRV+l/chEYJyEci5LfpQ2nYV+7VvhZ3pe7DUyKXb9panKS44PRlf1DsYHdYYVH7Qn6Jxb3OMF1WHyvu4hwN0kaxSev+Z03thBce8q9HK+xGq6f4LWTB2nBtljs+zbDLiIO3PH3LtTzwRUs0YwH7+2kc9qi8edd2aA54H82wfpS6ELs6MJlKDYD8jLzXcQ9LI+1l3f4LJ0jFGS7KyHPZgpOhhrXudjyVxJnKCCVSiSoZm7Bj1CvhmFQzekOOSyolTrjRxuBPvHOHEIeFkgd60vKtQL0Fe/sqWY6V5xrn/vozlUnQ3Px8txdpiB17uddSB/2tSMUNlQ+smT3S31UGI+JkveHqYqW1NriXEN4lOL5e/0TBw1r0npR8jcpc9QZj8K8dhRbZP/tlQd9RobTaQZ394neCowNAiymJfXSWUw62pquQwVv8UMdgCCUkroZ/NyO3fLBMMO3nw9wyumlmkez0MvmtCa46EgeISRhH6bghD/FMp8FXU85vm7P8p6lzySDLSA=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
